import fs from 'node:fs';
import path from 'node:path';
import { ensureDir, ROOT } from './lib/config.js';

/**
 * The three typefaces, fetched from Google Fonts and written into the bundle.
 *
 * They used to be a `<link>` to `fonts.googleapis.com` in `index.html`, which
 * costs the first paint two round trips to a third party — a DNS lookup and a
 * TLS handshake to `googleapis`, then the same again to `gstatic` for the files
 * the stylesheet names, all of it before a single letter can be drawn. That is
 * the one thing on this site a search engine measures directly and reports as a
 * ranking signal, and it buys nothing: the files never change.
 *
 * So they are served from our own origin, bundled by Vite like any other asset,
 * which also means they are hashed, cached for a year and precached by the
 * service worker along with everything else.
 *
 * This script is what makes that repeatable rather than a folder somebody once
 * downloaded. It is run by hand — `pnpm fonts:build` — when a weight is added
 * or a face is replaced; CI never runs it and does not need to.
 *
 * The subsets are chosen, not taken whole: Google splits every face into six by
 * alphabet, and this catalogue is written in two of them. Greek and Vietnamese
 * would be a third of the bytes for glyphs no page has ever asked for. The
 * `unicode-range` of each rule is kept exactly as served, so a browser still
 * fetches only the alphabet it is about to draw.
 */

/** Exactly what `index.html` used to ask `fonts.googleapis.com` for. */
const QUERY =
  'family=Unbounded:wght@500;700&family=Onest:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap';

/** The alphabets the catalogue is written in, plus what a university name needs. */
const SUBSETS = new Set(['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext']);

/** A Chrome, so that Google answers with woff2 rather than with ttf. */
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const OUT = path.join(ROOT, 'src/fonts');

type Face = {
  family: string;
  weight: string;
  subset: string;
  range: string;
  url: string;
  /** What the file is called on disk — readable, and stable across refetches. */
  file: string;
};

/** `@font-face { … }` as served, split into the parts that matter. */
function parse(css: string): Face[] {
  const faces: Face[] = [];
  // The comment before each block is the only place the subset is named.
  const blocks = css.split('/*').slice(1);
  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf('*/')).trim();
    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1];
    const url = /url\((https:[^)]+)\)/.exec(block)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1];
    if (!family || !weight || !url || !range) continue;
    if (!SUBSETS.has(subset)) continue;
    const slug = family.toLowerCase().replace(/\s+/g, '-');
    faces.push({
      family,
      weight,
      subset,
      range: range.trim(),
      url,
      file: `${slug}-${weight}-${subset}.woff2`,
    });
  }
  return faces;
}

/**
 * The stylesheet the app imports, written against the files on disk.
 *
 * Relative URLs on purpose: Vite resolves them, hashes the file and rewrites
 * the reference against whatever `base` the build was given. An absolute
 * `/fonts/…` would be a 404 on a fork served from `/<repo>/`, and that is a
 * failure nobody sees until somebody forks — see docs/hosting.md.
 */
function stylesheet(faces: Face[]): string {
  const head = [
    '/*',
    ' * Generated by `pnpm fonts:build` — do not edit by hand.',
    ' *',
    ' * The three typefaces, served from our own origin instead of from Google.',
    ' * scripts/fonts.ts says why, where they came from and what a refetch costs.',
    ' *',
    ' * Unbounded, Onest and JetBrains Mono are all under the SIL Open Font',
    ' * License 1.1 — src/fonts/README.md carries the notice they ask for.',
    ' */',
    '',
  ].join('\n');

  const rules = faces.map((face) =>
    [
      '@font-face {',
      `  font-family: '${face.family}';`,
      '  font-style: normal;',
      `  font-weight: ${face.weight};`,
      // The letters appear in a fallback face and are replaced when the real
      // one lands, rather than the page holding a blank space for it. On a
      // slow connection that is the difference between a readable page and an
      // empty one.
      '  font-display: swap;',
      `  src: url('./fonts/${face.file}') format('woff2');`,
      `  unicode-range: ${face.range};`,
      '}',
    ].join('\n')
  );

  return `${head}${rules.join('\n\n')}\n`;
}

async function main(): Promise<void> {
  const response = await fetch(`https://fonts.googleapis.com/css2?${QUERY}`, {
    headers: { 'user-agent': UA },
  });
  if (!response.ok) {
    console.error(`✗ Google Fonts answered ${response.status}`);
    process.exit(1);
  }
  const faces = parse(await response.text());
  if (!faces.length) {
    console.error('✗ no @font-face rules matched — the CSS format has changed, read scripts/fonts.ts');
    process.exit(1);
  }

  ensureDir(OUT);
  let bytes = 0;
  for (const face of faces) {
    const file = path.join(OUT, face.file);
    const woff2 = Buffer.from(await (await fetch(face.url, { headers: { 'user-agent': UA } })).arrayBuffer());
    fs.writeFileSync(file, woff2);
    bytes += woff2.length;
  }

  fs.writeFileSync(path.join(ROOT, 'src/fonts.css'), stylesheet(faces), 'utf8');

  const families = [...new Set(faces.map((face) => face.family))];
  console.log(
    `✓ ${faces.length} files, ${Math.round(bytes / 1024)} KB — ${families.join(', ')}\n` +
      '  src/fonts.css rewritten; import it from src/index.css if it is not already.'
  );
}

await main();
