import { boxOf } from '../shared/polygon.js';
import type { MapConfig } from '../shared/mapgen.js';
import { paths } from './lib/config.js';
import { anchorOf, ringFrom, writeMapFile, type FileTerritory } from './lib/map-file.js';
import { buildWorld, readOverrides } from './lib/map-world.js';
import { loadSources } from './lib/sources.js';
import { reportRunError } from './lib/exit.js';

/**
 * Draws the same world for a window taller than it is wide, and writes
 * `public/map-portrait.svg`.
 *
 * The wide map is a picture of three continents side by side. Fitted into a
 * phone held upright it is a strip of land across the middle of a lot of water,
 * with the names too small to read — the shape of the paper is wrong, and no
 * amount of zooming fixes the shape of the paper. So the world is laid out
 * again for that paper: the same territories, the same areas, the same
 * dependency order read bottom to top inside each continent, only stacked
 * instead of ranged.
 *
 * Nothing is hand-placed. This is the generator with a different config, which
 * is what keeps the two maps agreeing about the catalogue: add a domain and both
 * are one command away from carrying it.
 *
 *   pnpm map:portrait
 *   pnpm map:portrait --seed=9 --height=1600   # any knob, to try a variant
 */

/**
 * The portrait world.
 *
 * `packing` is the whole point. The rest is what that costs:
 *
 * - **maxStretch below 1**, so the continents come out a little wider than they
 *   are tall. Stacked, every unit of a continent's height is spent twice —
 *   once on itself and once on pushing the next two further down — while its
 *   width is free, and three narrow continents in a tall canvas leave the paper
 *   empty down both sides. Not lower than this, though: at 0.7 the rows inside
 *   a continent start crowding each other and the dependency order stops
 *   reading bottom to top, which is a claim the map is not allowed to break for
 *   the sake of its own proportions. `map:preview` prints that share.
 * - **A larger cell.** The same land drawn on 20-unit hexes instead of 16 is a
 *   third fewer pieces of relief and a third fewer waves — and this is the map
 *   that runs on the weaker machine. It also reads better small: at the size a
 *   phone draws a continent, a 16-unit cell of forest is a smudge.
 * - **A tighter strait**, for the same reason as the stretch: the gaps are
 *   stacked now, so each one is spent on the axis that is already the long one.
 *
 * The canvas is not what the reader sees — the screen fits the *land* to the
 * window and lets the water run off the edges. What matters is the shape the
 * land comes out, which is what the report at the end of a run says.
 */
const PORTRAIT: Partial<MapConfig> = {
  packing: 'column',
  width: 1180,
  height: 1560,
  maxStretch: 0.8,
  hexR: 20,
  strait: 76,
};

/** How tall a phone's map area is against its width, roughly. What we aim at. */
const TARGET_ASPECT = 0.6;

function main(): void {
  const overrides = { ...PORTRAIT, ...readOverrides(process.argv.slice(2)) };
  const { map, levels } = buildWorld(overrides);
  if (levels.cycle) {
    console.warn(`! цикл в dependsOn: ${levels.cycle.join(' → ')}`);
  }

  // The shapeId is the app's handle on a territory and lives in domains.yaml,
  // not in the generator — which knows domains by id and nothing else.
  const { domains } = loadSources();
  const shapeIdOf = new Map(domains.map((domain) => [domain.id, domain.shapeId]));

  const territories: FileTerritory[] = map.territories.map((territory) => {
    const shapeId = shapeIdOf.get(territory.id);
    if (!shapeId) throw new Error(`${territory.id} has no shapeId in domains.yaml`);
    return {
      shapeId,
      domainId: territory.id,
      continent: territory.continent,
      d: territory.path,
      // Measured off the outline rather than taken from the generator's own
      // hex-grid estimate, because the wide map's anchors are measured that way
      // too — the two files have to describe themselves identically or the
      // screen letters them differently.
      anchor: anchorOf(ringFrom(territory.path, `territory ${territory.id}`)),
    };
  });

  writeMapFile(paths.mapPortraitSvg, {
    viewBox: map.viewBox,
    landmasses: map.coasts.map((coast) => ({
      continent: coast.continent,
      kind: coast.kind,
      d: coast.path,
    })),
    territories,
    provenance: 'Generated by `pnpm map:portrait` — the same generator as the wide map, stacked.',
  });

  report(map.coasts.map((coast) => coast.path));
}

/**
 * What the land actually came out as.
 *
 * The canvas is scenery; the box the land fits in is what the screen fits to a
 * window, so that is the number worth printing. Too wide and the phone gets
 * bands of water above and below the map, too narrow and it gets them down the
 * sides.
 */
function report(coasts: string[]): void {
  const points = coasts.flatMap((d) => ringFrom(d, 'a coastline'));
  const land = boxOf(points);
  const aspect = land.width / land.height;
  const verdict =
    Math.abs(aspect - TARGET_ASPECT) < 0.08
      ? 'по форме телефона'
      : aspect > TARGET_ASPECT
        ? 'шире телефона — вода останется сверху и снизу'
        : 'уже телефона — вода останется по бокам';
  console.log(
    `  суша ${land.width.toFixed(0)}×${land.height.toFixed(0)} · ` +
      `отношение ${aspect.toFixed(2)} при ${TARGET_ASPECT} — ${verdict}`
  );
}

try {
  main();
} catch (error) {
  reportRunError(error);
}
